name: Pharmaceuticals Finance Data Analysis

on:
  push:
    branches: develop
  pull_request:
    branches: develop

jobs:
  build-and-analyze:
    runs-on: windows-latest  # Use Windows runner

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.12 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy matplotlib seaborn scipy

    - name: Install Additional Dependencies for Windows
      run: |
        pip install scikit-learn
        pip install pywin32  # If you need Windows-specific dependencies
